version: '3.5'
services:
  timescale:
    image: kolan1992/backend-test-db:0.0.1
    hostname: timescale
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 172.18.0.5




networks:
  backend:
    name: 'backend'
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  postgres-data: